inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"

Layout/LineLength:
  Max: 150

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/GuardClause:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - spec/factories/*
    - spec/support/*
    - config/routes.rb

Metrics/MethodLength:
  Max: 30
