AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"

Layout/LineLength:
  Max: 150

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/RedundantReturn:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - spec/factories/*
    - spec/support/*

Metrics/MethodLength:
  Max: 30
