version: '3.7'
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - boookshelf_postgres:/var/lib/postgresql/data
    ports:
      - 15432:5432
volumes:
  boookshelf_postgres:
    external: true
