version: '3.7'
services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    volumes:
      - my_boookshelf_db:/var/lib/postgresql/data:delegated
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/webapp:cached
      - ./node_modules:/webapp/node_modules:delegated
      - app-public:/webapp/public
      - app-tmp:/webapp/tmp
      - app-log:/webapp/log
    depends_on:
      - db
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - nginx-log:/var/log/nginx
      - app-public:/webapp/public:cached
      - app-tmp:/webapp/tmp:cached
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  my_boookshelf_db:
  app-public:
  app-tmp:
  app-log:
  nginx-log:
