version: '3.7'
services:
  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    volumes:
      - my_boookshelf_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/app:cached
      - ./node_modules:/app/node_modules:delegated
    ports:
      - 3000:3000
    depends_on:
      - db

volumes:
  my_boookshelf_db:
